/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    // But you can create a sidebar manually
    tutorialSidebar: [
        'intro',
        {
            type: 'category',
            label: '开始',
            collapsible: true,
            items: [
                'start/start',
                'start/sign-up-and-in',
                'start/user-setting'
            ],
        },
        {
            type: 'category',
            label: '比赛/班级',
            collapsible: true,
            items: [
                'contest/contest',
                'contest/join-contest',
                'contest/exercise'
            ]
        }
    ],
};

module.exports = sidebars;
